# What Python version is installed where:
# http://www.appveyor.com/docs/installed-software#python

environment:
  matrix:
    - PYTHON: "C:\\Python27"
      TOXENV: "py27"

    - PYTHON: "C:\\Python27-x64"
      TOXENV: "py27"

    - PYTHON: "C:\\Python34"
      TOXENV: "py34"

    - PYTHON: "C:\\Python34-x64"
      TOXENV: "py34"

    - PYTHON: "C:\\Python35"
      TOXENV: "py35"

    - PYTHON: "C:\\Python35-x64"
      TOXENV: "py35"

    - PYTHON: "C:\\Python36"
      TOXENV: "py36"

    - PYTHON: "C:\\Python36-x64"
      TOXENV: "py36"

init:
  - set PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
  - "git config --system http.sslcainfo \"C:\\Program Files\\Git\\mingw64\\ssl\\certs\\ca-bundle.crt\""
  - "%PYTHON%/python -V"
  - "%PYTHON%/python -c \"import struct;print(8 * struct.calcsize(\'P\'))\""

install:
  - "%PYTHON%/Scripts/easy_install -U pip"
  - "%PYTHON%/Scripts/pip install tox"
  - "%PYTHON%/Scripts/pip install wheel"

build: false  # Not a C# project, build stuff at the test step instead.

test_script:
  - "%PYTHON%/Scripts/tox"

after_test:
  - "%PYTHON%/python setup.py bdist_wheel"
  - ps: "ls dist"

on_success:
    # Report coverage results to codecov.io
    # and export tox environment variables
    - "%PYTHON%/Scripts/pip install codecov"
    - set OS=WINDOWS
    - "%PYTHON%/Scripts/codecov -e TOXENV OS"

artifacts:
  - path: dist\*

#on_success:
#  - TODO: upload the content of dist/*.whl to a public wheelhouse
