environment:
  matrix:
    # - PYTHON: "C:\\Python27"
    #   PYTHON_VERSION: "2.7.8"
    #   PYTHON_ARCH: "32"

    # - PYTHON: "C:\\Python27-64"
    #   PYTHON_VERSION: "2.7.8"
    #   WINDOWS_SDK_VERSION: "v7.0"
    #   PYTHON_ARCH: "64"

    - PYTHON: "C:\\Python33"
      PYTHON_VERSION: "3.3.5"
      PYTHON_ARCH: "32"

    # - PYTHON: "C:\\Python34-64"
    #   PYTHON_VERSION: "3.4.1"
    #   WINDOWS_SDK_VERSION: "v7.1"
    #   PYTHON_ARCH: "64"

init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"

install:
  - "appveyor/setup_build_env.cmd"
  - "powershell appveyor/install.ps1"

build: false  # Not a C# project, build stuff at the test step instead.

test_script:
  - "%PYTHON%/python setup.py test"

after_test:
  - "%PYTHON%/python setup.py bdist_wheel"
  - ps: "ls dist"

artifacts:
  - path: dist\*

#on_success:
#  - TODO: upload the content of dist/*.whl to a public wheelhouse